services:
  frontend:
    build:
      context: ./leaves
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - brainforest-network

  backend:
    build:
      context: ./sap
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/brainforest
    depends_on:
      - db
    networks:
      - brainforest-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=brainforest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - brainforest-network

networks:
  brainforest-network:
    driver: bridge

volumes:
  postgres_data:
