services:
  frontend:
    build:
      context: ./leaves
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - brainforest-network
    restart: unless-stopped

  backend:
    build:
      context: ./sap
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/brainforest
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - brainforest-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=brainforest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - brainforest-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d brainforest"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  brainforest-network:
    driver: bridge

volumes:
  postgres_data:
